"""Phase 1 tests: LUT constants, rotation, golden-section spiral, atom-type
/ radius / charge classifiers.

References are generated by `docking/tests/julia_ref/generate_refs.jl`. Each
test loads the relevant `phase1_*.h5` and asserts numerical agreement.
"""

from __future__ import annotations

import numpy as np
import pytest
import torch

from zdock import atomtypes
from zdock.geom import golden_section_spiral, rotate


# --------------------------------------------------------------------- tables


def test_ace_score_matches_julia(load_ref, device, dtype, tol):
    ref = load_ref("phase1", "tables")
    got = atomtypes.ace_score(device=device, dtype=dtype)
    expected = torch.as_tensor(ref["ace_score"], device=device, dtype=dtype)
    torch.testing.assert_close(got, expected, **tol)


def test_iface_ij_matches_julia(load_ref, device, dtype, tol):
    ref = load_ref("phase1", "tables")
    got_mat = atomtypes.iface_ij(device=device, dtype=dtype, flat=False)
    expected_mat = torch.as_tensor(ref["iface_ij"], device=device, dtype=dtype)
    torch.testing.assert_close(got_mat, expected_mat, **tol)

    got_flat = atomtypes.iface_ij(device=device, dtype=dtype, flat=True)
    expected_flat = torch.as_tensor(ref["iface_ij_flat"], device=device, dtype=dtype)
    torch.testing.assert_close(got_flat, expected_flat, **tol)


def test_charge_score_matches_julia(load_ref, device, dtype, tol):
    ref = load_ref("phase1", "tables")
    got = atomtypes.charge_score(device=device, dtype=dtype)
    expected = torch.as_tensor(ref["charge_score"], device=device, dtype=dtype)
    torch.testing.assert_close(got, expected, **tol)


# ------------------------------------------------------------- golden spiral


def test_golden_section_spiral_matches_julia(load_ref, device, dtype, tol):
    ref = load_ref("phase1", "spiral")
    n = int(ref["npoint"])
    got = golden_section_spiral(n, device=device, dtype=dtype)
    # Julia stores (n, 3); HDF5 column-major → numpy sees (3, n). Transpose.
    expected = torch.as_tensor(np.asarray(ref["points"]).T, device=device, dtype=dtype)
    assert got.shape == expected.shape == (n, 3)
    # Relax tol for float32: MPS/CUDA cos/sin have inherent ~1e-5 precision
    # and large phi angles amplify it even after remainder(2π). The spiral
    # is a one-shot precomputation whose users (SASA) compare at 1e-2 tol.
    spiral_tol = tol if dtype == torch.float64 else dict(atol=2e-4, rtol=5e-3)
    torch.testing.assert_close(got, expected, **spiral_tol)


# ----------------------------------------------------------------- rotation


def test_rotate_matches_julia(load_ref, device, dtype, tol):
    ref = load_ref("phase1", "rotate")
    q = torch.as_tensor(ref["q"], device=device, dtype=dtype)
    x = torch.as_tensor(ref["x_in"], device=device, dtype=dtype)
    y = torch.as_tensor(ref["y_in"], device=device, dtype=dtype)
    z = torch.as_tensor(ref["z_in"], device=device, dtype=dtype)

    xn, yn, zn = rotate(x, y, z, q)

    torch.testing.assert_close(
        xn, torch.as_tensor(ref["x_out"], device=device, dtype=dtype), **tol
    )
    torch.testing.assert_close(
        yn, torch.as_tensor(ref["y_out"], device=device, dtype=dtype), **tol
    )
    torch.testing.assert_close(
        zn, torch.as_tensor(ref["z_out"], device=device, dtype=dtype), **tol
    )


# ------------------------------------------------------ atom-type classifier


@pytest.fixture(scope="module")
def receptor_ref(load_ref):
    # This is not a session fixture (load_ref depends on refs_root which is
    # session-scoped, but we can still cache module-wide via @lru). Skipping
    # full caching for simplicity.
    return load_ref("phase1", "receptor_tables")


@pytest.fixture(scope="module")
def ligand_ref(load_ref):
    return load_ref("phase1", "ligand_tables")


def test_set_radius_receptor_matches_julia(receptor_ref, device, dtype, tol):
    got = atomtypes.set_radius(
        receptor_ref["atomname"], device=device, dtype=dtype
    )
    expected = torch.as_tensor(
        receptor_ref["radius"], device=device, dtype=dtype
    )
    torch.testing.assert_close(got, expected, **tol)


def test_set_radius_ligand_matches_julia(ligand_ref, device, dtype, tol):
    got = atomtypes.set_radius(
        ligand_ref["atomname"], device=device, dtype=dtype
    )
    expected = torch.as_tensor(
        ligand_ref["radius"], device=device, dtype=dtype
    )
    torch.testing.assert_close(got, expected, **tol)


def test_set_atomtype_id_receptor_matches_julia(receptor_ref):
    got = atomtypes.set_atomtype_id(
        receptor_ref["resname"], receptor_ref["atomname"]
    )
    expected = torch.as_tensor(np.asarray(receptor_ref["atomtype_id"]), dtype=torch.int64)
    # Identity per atom — the count of matching IDs tells us how close we are.
    match_rate = (got == expected).float().mean().item()
    assert match_rate >= 0.999, (
        f"atomtype_id only matches {match_rate:.4%} of atoms; likely a rule-ladder "
        f"mismatch with docking.jl's set_atomtype_id."
    )


def test_set_atomtype_id_ligand_matches_julia(ligand_ref):
    got = atomtypes.set_atomtype_id(
        ligand_ref["resname"], ligand_ref["atomname"]
    )
    expected = torch.as_tensor(np.asarray(ligand_ref["atomtype_id"]), dtype=torch.int64)
    match_rate = (got == expected).float().mean().item()
    assert match_rate >= 0.999, (
        f"ligand atomtype_id match rate {match_rate:.4%} too low."
    )


def _pro_n_mask(resnames, atomnames) -> torch.Tensor:
    """Positions where our Python `set_charge` intentionally diverges from the
    Julia reference: proline backbone nitrogens. Julia's ladder evaluated
    `a == "N"` *before* the `PRO + N` branch so PRO/N atoms got charge id 1
    or 11 depending on sequence position. The Python port fixes this so they
    always get charge id 7 (the intended PRO-N class in `_CHARGE_SCORE`)."""
    return torch.tensor(
        [r == "PRO" and a == "N" for r, a in zip(resnames, atomnames)],
        dtype=torch.bool,
    )


def test_set_charge_receptor_matches_julia(receptor_ref):
    got = atomtypes.set_charge(
        receptor_ref["resname"], receptor_ref["atomname"]
    )
    expected = torch.as_tensor(np.asarray(receptor_ref["charge"]), dtype=torch.int64)
    pro_n = _pro_n_mask(receptor_ref["resname"], receptor_ref["atomname"])
    # Outside PRO/N positions, we must match Julia exactly.
    torch.testing.assert_close(got[~pro_n], expected[~pro_n])
    # At PRO/N positions, the Python port always returns 7 (the fix).
    assert pro_n.any(), "receptor reference unexpectedly has no PRO/N atoms"
    assert torch.all(got[pro_n] == 7)


def test_set_charge_ligand_matches_julia(ligand_ref):
    got = atomtypes.set_charge(ligand_ref["resname"], ligand_ref["atomname"])
    expected = torch.as_tensor(np.asarray(ligand_ref["charge"]), dtype=torch.int64)
    pro_n = _pro_n_mask(ligand_ref["resname"], ligand_ref["atomname"])
    torch.testing.assert_close(got[~pro_n], expected[~pro_n])
    if pro_n.any():
        assert torch.all(got[pro_n] == 7)


# --------------------------------------------------------- set_charge regressions


def test_set_charge_pro_n_returns_7():
    """Regression: PRO/N must map to charge id 7, not be swallowed by the
    generic `a == "N"` branch (bug: previously returned 1)."""
    got = atomtypes.set_charge(["PRO"], ["N"])
    assert got.tolist() == [7]


def test_set_charge_first_plain_n_is_terminal():
    """The first non-PRO backbone N in the sequence is still the N-terminus
    (charge id 1)."""
    got = atomtypes.set_charge(["ALA"], ["N"])
    assert got.tolist() == [1]


def test_set_charge_later_plain_n_is_generic():
    """Non-first non-PRO backbone N gets the generic amide nitrogen id (11)."""
    got = atomtypes.set_charge(["ALA", "GLY"], ["N", "N"])
    assert got.tolist() == [1, 11]


def test_set_charge_pro_n_does_not_consume_first_n_slot():
    """A leading PRO/N must not steal the TERMINAL-N (1) assignment from a
    following plain N — it is classified independently as PRO N (7)."""
    got = atomtypes.set_charge(["PRO", "ALA"], ["N", "N"])
    assert got.tolist() == [7, 1]


def test_set_charge_oxt_is_terminal_o():
    """OXT is always the C-terminal oxygen (charge id 2), independent of
    residue name."""
    got = atomtypes.set_charge(["ALA"], ["OXT"])
    assert got.tolist() == [2]


def test_set_charge_mixed_sequence():
    """Mixed sequence smoke test covering terminal-N, PRO/N, plain N, O, OXT."""
    resnames = ["ALA", "PRO", "GLY", "ALA", "ALA"]
    atomnames = ["N", "N", "N", "O", "OXT"]
    got = atomtypes.set_charge(resnames, atomnames)
    assert got.tolist() == [1, 7, 11, 10, 2]
